import { serializeDaysOfWeek } from '../../domain/schedule';
import type { Medication, MedicationSchedule, MedicationStatus } from '../../domain/types';
import { newId } from '../../lib/id';
import { mapMedication, mapSchedule, optText } from '../rows';
import { NotFoundError, toBit, type SqlDatabase, type SqlExecutor } from '../sql';
import { logAudit } from './audit';

export interface ScheduleInput {
  timeOfDay: string;
  daysOfWeek: number[];
  doseLabel?: string | null;
}

export interface MedicationInput {
  name: string;
  strength?: string | null;
  form?: string | null;
  doseInstructions?: string;
  prescriber?: string | null;
  startDate: string;
  endDate?: string | null;
  status?: MedicationStatus;
  asNeeded?: boolean;
  refillSupplyCount?: number | null;
  refillUnitsPerDose?: number | null;
  refillThresholdDays?: number | null;
  refillReminderDate?: string | null;
  notes?: string | null;
  schedules: ScheduleInput[];
}

export interface MedicationWithSchedules {
  medication: Medication;
  schedules: MedicationSchedule[];
}

function scheduleSignature(s: { timeOfDay: string; daysOfWeek: number[]; doseLabel?: string | null }): string {
  return `${s.timeOfDay}|${serializeDaysOfWeek(s.daysOfWeek)}|${optText(s.doseLabel) ?? ''}`;
}

async function insertSchedule(tx: SqlExecutor, profileId: string, medicationId: string, s: ScheduleInput, now: string): Promise<void> {
  await tx.runAsync(
    `INSERT INTO medication_schedules (id, profile_id, medication_id, time_of_day, days_of_week, dose_label, active, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)`,
    [newId(), profileId, medicationId, s.timeOfDay, serializeDaysOfWeek(s.daysOfWeek), optText(s.doseLabel), now, now],
  );
}

export async function createMedication(db: SqlDatabase, profileId: string, input: MedicationInput, now = new Date().toISOString()): Promise<string> {
  const id = newId();
  await db.transaction(async (tx) => {
    await tx.runAsync(
      `INSERT INTO medications (id, profile_id, name, strength, form, dose_instructions, prescriber, start_date, end_date, status, as_needed,
        refill_supply_count, refill_units_per_dose, refill_threshold_days, refill_reminder_date, supply_updated_at, notes, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        profileId,
        input.name.trim(),
        optText(input.strength),
        optText(input.form),
        (input.doseInstructions ?? '').trim(),
        optText(input.prescriber),
        input.startDate,
        optText(input.endDate),
        input.status ?? 'active',
        toBit(input.asNeeded ?? false),
        input.refillSupplyCount ?? null,
        input.refillUnitsPerDose ?? null,
        input.refillThresholdDays ?? null,
        optText(input.refillReminderDate),
        input.refillSupplyCount !== null && input.refillSupplyCount !== undefined ? now : null,
        optText(input.notes),
        now,
        now,
      ],
    );
    if (!input.asNeeded) {
      for (const s of input.schedules) await insertSchedule(tx, profileId, id, s, now);
    }
    await logAudit(tx, { profileId, action: 'create', entityType: 'medication', entityId: id, at: now });
  });
  return id;
}

/**
 * Updates a medication and reconciles its schedules: unchanged schedules are kept (so their dose
 * history stays linked), removed ones are deactivated, new ones inserted. Future untouched dose
 * events are regenerated by syncDoseEvents afterwards.
 */
export async function updateMedication(
  db: SqlDatabase,
  profileId: string,
  id: string,
  input: MedicationInput,
  now = new Date().toISOString(),
): Promise<void> {
  await db.transaction(async (tx) => {
    const existing = await tx.getFirstAsync<{ refill_supply_count: number | null; supply_updated_at: string | null }>(
      'SELECT refill_supply_count, supply_updated_at FROM medications WHERE id = ? AND profile_id = ?',
      [id, profileId],
    );
    if (!existing) throw new NotFoundError('Medication');
    const newSupply = input.refillSupplyCount ?? null;
    const supplyUpdatedAt = newSupply !== existing.refill_supply_count ? (newSupply === null ? null : now) : existing.supply_updated_at;
    await tx.runAsync(
      `UPDATE medications SET name = ?, strength = ?, form = ?, dose_instructions = ?, prescriber = ?, start_date = ?, end_date = ?, status = ?,
        as_needed = ?, refill_supply_count = ?, refill_units_per_dose = ?, refill_threshold_days = ?, refill_reminder_date = ?,
        supply_updated_at = ?, notes = ?, updated_at = ? WHERE id = ? AND profile_id = ?`,
      [
        input.name.trim(),
        optText(input.strength),
        optText(input.form),
        (input.doseInstructions ?? '').trim(),
        optText(input.prescriber),
        input.startDate,
        optText(input.endDate),
        input.status ?? 'active',
        toBit(input.asNeeded ?? false),
        newSupply,
        input.refillUnitsPerDose ?? null,
        input.refillThresholdDays ?? null,
        optText(input.refillReminderDate),
        supplyUpdatedAt,
        optText(input.notes),
        now,
        id,
        profileId,
      ],
    );

    const current = (
      await tx.getAllAsync<Record<string, unknown>>('SELECT * FROM medication_schedules WHERE medication_id = ? AND profile_id = ? AND active = 1', [
        id,
        profileId,
      ])
    ).map(mapSchedule);
    const wanted = input.asNeeded ? [] : input.schedules;
    const wantedSigs = new Set(wanted.map(scheduleSignature));
    const keptSigs = new Set<string>();
    for (const s of current) {
      const sig = scheduleSignature(s);
      if (wantedSigs.has(sig) && !keptSigs.has(sig)) {
        keptSigs.add(sig);
      } else {
        await tx.runAsync('UPDATE medication_schedules SET active = 0, updated_at = ? WHERE id = ? AND profile_id = ?', [now, s.id, profileId]);
      }
    }
    for (const s of wanted) {
      const sig = scheduleSignature(s);
      if (!keptSigs.has(sig)) {
        await insertSchedule(tx, profileId, id, s, now);
        keptSigs.add(sig);
      }
    }
    await logAudit(tx, { profileId, action: 'update', entityType: 'medication', entityId: id, at: now });
  });
}

export async function setMedicationStatus(db: SqlDatabase, profileId: string, id: string, status: MedicationStatus, now = new Date().toISOString()): Promise<void> {
  await db.transaction(async (tx) => {
    const res = await tx.runAsync('UPDATE medications SET status = ?, updated_at = ? WHERE id = ? AND profile_id = ?', [status, now, id, profileId]);
    if (res.changes === 0) throw new NotFoundError('Medication');
    await logAudit(tx, { profileId, action: 'status_change', entityType: 'medication', entityId: id, detail: `status: ${status}`, at: now });
  });
}

/** Records a new supply count (e.g. after picking up a refill). */
export async function updateSupply(db: SqlDatabase, profileId: string, id: string, count: number, now = new Date().toISOString()): Promise<void> {
  const res = await db.runAsync(
    'UPDATE medications SET refill_supply_count = ?, supply_updated_at = ?, refill_reminder_date = NULL, updated_at = ? WHERE id = ? AND profile_id = ?',
    [count, now, now, id, profileId],
  );
  if (res.changes === 0) throw new NotFoundError('Medication');
}

export async function deleteMedication(db: SqlDatabase, profileId: string, id: string): Promise<void> {
  await db.transaction(async (tx) => {
    const res = await tx.runAsync('DELETE FROM medications WHERE id = ? AND profile_id = ?', [id, profileId]);
    if (res.changes === 0) throw new NotFoundError('Medication');
    await logAudit(tx, { profileId, action: 'delete', entityType: 'medication', entityId: id });
  });
}

export async function listMedications(db: SqlExecutor, profileId: string): Promise<MedicationWithSchedules[]> {
  const meds = (
    await db.getAllAsync<Record<string, unknown>>(
      "SELECT * FROM medications WHERE profile_id = ? ORDER BY CASE status WHEN 'active' THEN 0 WHEN 'paused' THEN 1 ELSE 2 END, name COLLATE NOCASE",
      [profileId],
    )
  ).map(mapMedication);
  const schedules = (
    await db.getAllAsync<Record<string, unknown>>('SELECT * FROM medication_schedules WHERE profile_id = ? AND active = 1 ORDER BY time_of_day', [
      profileId,
    ])
  ).map(mapSchedule);
  return meds.map((m) => ({ medication: m, schedules: schedules.filter((s) => s.medicationId === m.id) }));
}

export async function getMedication(db: SqlExecutor, profileId: string, id: string): Promise<MedicationWithSchedules | null> {
  const r = await db.getFirstAsync<Record<string, unknown>>('SELECT * FROM medications WHERE id = ? AND profile_id = ?', [id, profileId]);
  if (!r) return null;
  const schedules = (
    await db.getAllAsync<Record<string, unknown>>(
      'SELECT * FROM medication_schedules WHERE medication_id = ? AND profile_id = ? AND active = 1 ORDER BY time_of_day',
      [id, profileId],
    )
  ).map(mapSchedule);
  return { medication: mapMedication(r), schedules };
}

export interface ActiveScheduleRow {
  scheduleId: string;
  medicationId: string;
  timeOfDay: string;
  daysOfWeek: number[];
  startDate: string;
  endDate: string | null;
  scheduleCreatedAt: string;
}

/** Active schedules of active, scheduled (not as-needed) medications. */
export async function listActiveSchedules(db: SqlExecutor, profileId: string): Promise<ActiveScheduleRow[]> {
  const rows = await db.getAllAsync<{
    id: string;
    medication_id: string;
    time_of_day: string;
    days_of_week: string;
    start_date: string;
    end_date: string | null;
    created_at: string;
  }>(
    `SELECT s.id, s.medication_id, s.time_of_day, s.days_of_week, m.start_date, m.end_date, s.created_at
       FROM medication_schedules s JOIN medications m ON m.id = s.medication_id AND m.profile_id = s.profile_id
      WHERE s.profile_id = ? AND s.active = 1 AND m.status = 'active' AND m.as_needed = 0`,
    [profileId],
  );
  return rows.map((r) => ({
    scheduleId: r.id,
    medicationId: r.medication_id,
    timeOfDay: r.time_of_day,
    daysOfWeek: r.days_of_week ? r.days_of_week.split(',').map(Number) : [],
    startDate: r.start_date,
    endDate: r.end_date,
    scheduleCreatedAt: r.created_at,
  }));
}
